server: 
  port: 80
  servlet:
    context-path: /
    
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/db_book
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 580230SJQ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true